# Generated by Django 4.0.1 on 2022-01-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrupoC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('dire', models.CharField(max_length=40, verbose_name='dire')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name='apellido')),
                ('exp', models.CharField(max_length=50, verbose_name='exp')),
            ],
        ),
        migrations.AlterField(
            model_name='cerveza',
            name='grad_alcohol',
            field=models.FloatField(),
        ),
    ]
