# Generated by Django 4.0.1 on 2022-01-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrupoC', '0002_cerveceria_experiencia_alter_cerveza_grad_alcohol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='exp',
        ),
        migrations.AddField(
            model_name='experiencia',
            name='cerv_atend',
            field=models.CharField(max_length=40, null=True, verbose_name='¿A cual cerveceria fuiste?'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='cerv_tomada',
            field=models.CharField(max_length=40, null=True, verbose_name='¿Que cerveza tomaste?'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='punt_cerveceria',
            field=models.IntegerField(null=True, verbose_name='Puntaje Cerveceria'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='punt_cerveza',
            field=models.IntegerField(null=True, verbose_name='Puntaje Cerveza'),
        ),
        migrations.AlterField(
            model_name='cerveceria',
            name='dire',
            field=models.CharField(max_length=40, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='cerveceria',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cerveza',
            name='grad_alcohol',
            field=models.FloatField(verbose_name='ABV (%)'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='apellido',
            field=models.CharField(max_length=40, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='nombre',
            field=models.CharField(max_length=40, null=True, verbose_name='Nombre'),
        ),
    ]
